source 'https://rubygems.org'

gem 'builder'
gem 'font-awesome-sass'
gem 'middleman'
gem 'middleman-blog'
gem 'middleman-syntax'
gem 'middleman-livereload'
gem 'nokogiri'
gem 'rake'
gem 'redcarpet'
gem 'slim'
gem 'travis'
