version: 2
jobs:
  build:
    docker:
      - image: 'mozamimy/salmon'
        environment:
          AWS_ACCESS_KEY_ID: '$AWS_ACCESS_KEY_ID'
          AWS_SECRET_ACCESS_KEY: '$AWS_SECRET_ACCESS_KEY'
    steps:
      - 'checkout'
      - run:
          # TODO: Do not install AWS CLI while execution CI job.
          #       That should be bundled with Docker image for CI.
          name: 'Install AWS CLI'
          command: |
            apt-get -y update
            apt-get install -y awscli
      - run:
          name: 'Upload files to S3 bucket'
          command: |
            aws s3 sync build s3://mozami.me/ --delete
